export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    FETCH_SELECTED_PRODUCT : "FETCH_SELECTED_PRODUCT",
    SELECTED_PRODUCT_SUCCESS : "SELECTED_PRODUCT_SUCCESS",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT"
}